[language-server.tsgo]
command = "tsgo"
args = ["--lsp", "--stdio"]

[[language]]
name = "typescript"
language-servers = ["tsgo", "typescript-language-server"]

[[language]]
name = "tsx"
language-servers = ["tsgo", "typescript-language-server"]
